name: Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --configuration Release --no-restore
      
    - name: Get version from tag
      id: get_version
      run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
      
    - name: Generate meta.json
      run: |
        cat > meta.json << EOF
        {
          "category": "Metadata",
          "changelog": "See release notes",
          "description": "Forces Jellyfin to utilize original release date over standard release date in music metadata for proper sorting of re-releases and compilations.",
          "guid": "7c8df481-8eee-4b3a-9a3a-5c5e5e5e5e5e",
          "name": "Prefer Original Release Music Metadata",
          "overview": "Prefer original release dates in music metadata",
          "owner": "Jacob-Noah",
          "targetAbi": "10.11.0.0",
          "timestamp": "$(date -u +%Y-%m-%dT%H:%M:%SZ)",
          "version": "${{ steps.get_version.outputs.VERSION }}.0"
        }
        EOF
      
    - name: Create release artifact
      run: |
        mkdir -p release
        cp bin/Release/net8.0/Jellyfin.Plugin.PreferOriginalReleaseMusicMetadata.dll release/
        cp meta.json release/
        cd release
        zip -r ../jellyfin-prefer-original-release-music-metadata-${{ steps.get_version.outputs.VERSION }}.zip .
        
    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: jellyfin-prefer-original-release-music-metadata-${{ steps.get_version.outputs.VERSION }}.zip
        generate_release_notes: true
        body: |
          ## Jellyfin Prefer Original Release Music Metadata Plugin
          
          ### Installation
          1. Download the zip file below
          2. Extract the DLL and meta.json to your Jellyfin plugins directory:
             - Linux: `/var/lib/jellyfin/plugins/PreferOriginalReleaseMusicMetadata/`
             - Windows: `C:\ProgramData\Jellyfin\Server\plugins\PreferOriginalReleaseMusicMetadata\`
             - macOS: `/var/lib/jellyfin/plugins/PreferOriginalReleaseMusicMetadata/`
          3. Restart Jellyfin
          
          ### Requirements
          - Jellyfin 10.11.0 or later
          - .NET 8.0 runtime
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
